version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true
environment:
  matrix:

  - job_name: windows
    appveyor_build_worker_image: Visual Studio 2022

  - job_name: uwp
    appveyor_build_worker_image: Visual Studio 2022

for:
  -
    matrix:
      only:
        - job_name: windows

    cache: '%LOCALAPPDATA%\vcpkg\archives'

    install:
      - if not exist C:\Tools\vcpkg mkdir C:\Tools\vcpkg
      - cd C:\Tools\vcpkg
      - git pull
      - .\bootstrap-vcpkg.bat
      - cd %APPVEYOR_BUILD_FOLDER%

    before_build:
      - cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake .

    build:
      project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
      verbosity: minimal

    artifacts:
      - path: Debug\devilutionx.exe
        name: devilutionx.exe

  -
    matrix:
      only:
        - job_name: uwp

    before_build:
      - cd %APPVEYOR_BUILD_FOLDER%\Packaging\xbox-one
      - if exist ..\..\build rd /s /q ..\..\build

    build_script:
      - build.bat

    after_build:
      - cd %APPVEYOR_BUILD_FOLDER%

    artifacts:
      - path: devilutionx.zip
        name: devilutionx.zip
